apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: b2b
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: B2B project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: NetworkPolicy
    - group: '*'
      kind: ResourceQuota
    - group: '*'
      kind: LimitRange
  sourceRepos:
    - '*'
  roles:
    - name: ci-role
      description: Sync privileges for guestbook-dev
      policies:
        - 'p, proj:b2b:b2b, applications, *, b2b/*, allow'
        - 'p, proj:b2b:b2b, repositories, *, b2b/*, allow'

